#ifndef RESPONSE_H
#define RESPONSE_H

#define INTERNAL_ERROR "500 INTERNAL_ERROR %s\r\n"

#define REGISTER_OK "100 REGISTER_OK\r\n"
#define SYNTAX_ERROR "301 SYNTAX_ERROR\r\n"
#define INVALID_USERNAME "402 INVALID_USERNAME\r\n"
#define WEAK_PASSWORD "403 WEAK_PASSWORD\r\n"
#define USERNAME_EXISTS "403 USERNAME_EXISTS\r\n"

#define LOGIN_OK "110 LOGIN_OK\r\n"
#define ACCOUNT_NOT_FOUND "312 ACCOUNT_NOT_FOUND\r\n"
#define WRONG_PASSWORD "314 WRONG_PASSWORD\r\n"
#define ALREADY_LOGGED "313 ALREADY_LOGGED\r\n"
#define ACCOUNT_LOCKED "311 ACCOUNT_LOCKED\r\n"

#define LOGOUT_OK "134 LOGOUT_OK\r\n"
#define NOT_LOGGED "315 NOT_LOGGED\r\n"

#define WHOAMI_OK "201 WHOAMI_OK\r\n"

#define TEAM_CREATE_OK "120 TEAM_CREATE_OK\r\n"
#define INVALID_TEAM_NAME "405 INVALID_TEAM_NAME\r\n"
#define TEAM_NAME_EXISTS "333 TEAM_NAME_EXISTS\r\n"
#define TEAM_LIMIT_REACHED "334 TEAM_LIMIT_REACHED\r\n"

#define TEAM_DELETE_OK "129 TEAM_DELETE_OK\r\n"
#define TEAM_NOT_FOUND "323 TEAM_NOT_FOUND\r\n"
#define NOT_CREATOR "326 NOT_CREATOR\r\n"
#define LIST_TEAMS_OK "121 LIST_TEAMS_OK\r\n"

#define JOIN_REQUEST_OK "122 JOIN_REQUEST_OK\r\n"
#define ALREADY_IN_TEAM "336 ALREADY_IN_TEAM\r\n"
#define REQUEST_ALREADY_PENDING "330 REQUEST_ALREADY_PENDING\r\n"
#define TEAM_FULL "328 TEAM_FULL\r\n"

#define TEAM_INVITE_OK "125 TEAM_INVITE_OK\r\n"
#define USER_NOT_FOUND "324 USER_NOT_FOUND\r\n"
#define INVITE_ALREADY_PENDING "336 INVITE_ALREADY_PENDING\r\n"

#define ACCEPT_INVITE_OK "126 ACCEPT_INVITE_OK\r\n"

#define INVITE_DECLINE_OK "127 INVITE_DECLINE_OK\r\n"
#define NO_INVITE_FOUND "332 NO_INVITE_FOUND\r\n"

#define TEAM_LEAVE_OK "123 TEAM_LEAVE_OK\r\n"
#define NOT_IN_TEAM "327 NOT_IN_TEAM\r\n"

#define TEAM_MEMBER_LIST_OK "124 TEAM_MEMBER_LIST_OK\r\n"

#define KICK_MEMBER_OK "128 KICK_MEMBER_OK\r\n"
#define USER_NOT_IN_TEAM "335 USER_NOT_IN_TEAM\r\n"

#define CHALLENGE_SENT "130 CHALLENGE_SENT\r\n"
#define ALREADY_IN_CHALLENGE "336 ALREADY_IN_CHALLENGE\r\n"

#define CHALLENGE_ACCEPTED "131 CHALLENGE_ACCEPTED\r\n"
#define ALREADY_ACCEPTED "337 ALREADY_ACCEPTED\r\n"

#define CHALLENGE_DECLINED "132 CHALLENGE_DECLINED\r\n"
#define ALREADY_RESPONDED "338 ALREADY_RESPONDED\r\n"

#define CHALLENGE_CANCELED "133 CHALLENGE_CANCELED\r\n"
#define NOT_SENDER "339 NOT_SENDER\r\n"

#define START_MATCH_OK "126 START_MATCH_OK %s\r\n"
#define TEAM_NOT_FOUND "323 TEAM_NOT_FOUND %s\r\n"
#define NOT_CREATOR "326 NOT_CREATOR %s\r\n"
#define MATCH_STATE_ERROR "503 MATCH_STATE_ERROR %s\r\n"

#endif